import Link from 'next/link';

const roles = [
  ['Студент', 'Сегодня, расписание, задания и уведомления в одном спокойном потоке.', '/login'],
  ['Преподаватель', 'Группы, материалы, задания и посещаемость без лишних переходов.', 'https://teacher.napare.sano.ru'],
  ['Университет', 'Структура, пользователи, импорт расписания и состояние системы.', 'https://admin.napare.sano.ru'],
];

function ProductPreview() {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_70px_rgba(30,64,175,0.15)]">
    <div className="flex h-9 items-center gap-2 border-b border-slate-100 px-3"><span className="h-2 w-2 rounded-full bg-rose-300"/><span className="h-2 w-2 rounded-full bg-amber-300"/><span className="h-2 w-2 rounded-full bg-emerald-300"/><div className="ml-4 h-5 flex-1 rounded-md bg-slate-50"/></div>
    <div className="grid min-h-[320px] grid-cols-[112px_1fr] sm:grid-cols-[148px_1fr]">
      <aside className="bg-slate-950 p-3 text-white"><div className="mb-7 flex items-center gap-2 text-xs font-bold"><span className="flex h-6 w-6 items-center justify-center rounded-md bg-indigo-500">Н</span>НаПаре</div><div className="space-y-1 text-[10px] text-white/55">{['Сегодня', 'Расписание', 'Задания', 'Уведомления'].map((item, index) => <div key={item} className={`rounded-md px-2 py-2 ${index === 0 ? 'bg-indigo-500 text-white' : ''}`}>{item}</div>)}</div></aside>
      <div className="bg-slate-50 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] text-slate-400">НаПаре /</p><h3 className="text-lg font-bold text-slate-900">Сегодня</h3></div><span className="rounded-md bg-white px-2 py-1 text-[10px] text-slate-500">Учебный день</span></div><div className="grid gap-3 sm:grid-cols-[1.25fr_0.9fr]"><div className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-3 flex justify-between text-[10px] text-slate-400"><span>РАСПИСАНИЕ</span><span className="text-indigo-600">Все занятия</span></div>{[['09:00','Математический анализ','Ауд. 301'],['10:45','Программирование','Ауд. 412'],['13:00','Английский язык','Ауд. 210']].map(([time,name,room],i)=><div key={name} className={`flex gap-3 border-t border-slate-100 py-3 ${i===0?'border-l-2 border-l-emerald-500 pl-2':''}`}><span className="text-[10px] font-semibold text-slate-500">{time}</span><div><p className="text-xs font-semibold text-slate-800">{name}</p><p className="mt-0.5 text-[10px] text-slate-400">{room}</p></div></div>)}</div><div className="space-y-3"><div className="rounded-xl border border-emerald-100 bg-white p-3"><p className="text-[10px] font-semibold text-emerald-600">ТЕКУЩАЯ ПАРА</p><p className="mt-2 text-xs font-bold text-slate-800">Математический анализ</p><p className="mt-1 text-[10px] text-slate-400">09:00 — 10:30 · Ауд. 301</p><button className="mt-3 w-full rounded-md bg-indigo-600 py-1.5 text-[10px] font-semibold text-white">Открыть пространство</button></div><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-[10px] font-semibold text-slate-400">СЛЕДУЮЩАЯ ПАРА</p><p className="mt-2 text-xs font-bold text-slate-800">Программирование</p><p className="mt-1 text-[10px] text-slate-400">10:45 — 12:15 · Ауд. 412</p></div></div></div></div>
    </div>
  </div>;
}

export default function Home() {
  return <main className="min-h-screen bg-white">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/90 py-2 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2.5 rounded-lg p-2 text-lg font-bold tracking-tight text-slate-900"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600 text-sm text-white">Н</span>НаПаре</Link><nav className="hidden items-center gap-1 lg:flex"><a href="#product" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Возможности</a><a href="#roles" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Роли</a><a href="#how" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Как работает</a></nav><div className="flex items-center gap-2"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">Войти</Link><Link href="/register" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">Начать</Link></div></div></header>
    <section className="overflow-hidden bg-gradient-to-b from-indigo-50/70 to-white px-4 pb-16 pt-16 sm:px-6 lg:pb-20 lg:pt-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="mb-5 text-sm font-semibold text-indigo-600">Цифровая платформа университета</p><h1 className="max-w-xl text-4xl font-extrabold tracking-[-0.04em] text-slate-950 sm:text-6xl">Всё обучение —<br/><span className="text-indigo-600">в одном месте</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Расписание, пары, задания, уведомления, посещаемость и общение без десятка разных сервисов.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="rounded-xl bg-indigo-600 px-5 py-3 text-center text-sm font-semibold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700">Открыть НаПаре →</Link><a href="#product" className="rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50">Посмотреть возможности</a></div><div className="mt-9 grid max-w-md grid-cols-3 gap-4 text-xs text-slate-500"><span>Актуальное расписание</span><span>Всё в одном месте</span><span>Связь с группой</span></div></div><ProductPreview /></div></section>
    <section id="product" className="px-4 py-16 sm:px-6 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mx-auto mb-10 max-w-2xl text-center"><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Один понятный интерфейс для учебного дня</h2><p className="mt-4 text-slate-500">Студент видит главное сразу, преподаватель работает с группами, университет управляет системой.</p></div><ProductPreview /></div></section>
    <section id="roles" className="bg-slate-50 px-4 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-7xl"><div className="mb-10 text-center"><h2 className="text-3xl font-bold">Своя рабочая поверхность для каждой роли</h2><p className="mt-3 text-slate-500">Общий язык интерфейса, разные приоритеты и действия.</p></div><div className="grid gap-5 lg:grid-cols-3">{roles.map(([title, description, href]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-sm font-bold text-indigo-600">{title[0]}</div><h3 className="mt-5 text-xl font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p>{href.startsWith('http') ? <a href={href} className="mt-5 inline-block text-sm font-semibold text-indigo-600 hover:text-indigo-700">Открыть поверхность →</a> : <Link href={href} className="mt-5 inline-block text-sm font-semibold text-indigo-600 hover:text-indigo-700">Открыть поверхность →</Link>}</article>)}</div></div></section>
    <section id="how" className="px-4 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-7xl"><h2 className="text-center text-3xl font-bold">Как это работает</h2><div className="mt-10 grid gap-8 md:grid-cols-4">{[['01','Войдите','Создайте аккаунт или войдите через университет.'],['02','Выберите роль','Откройте рабочую поверхность для своей задачи.'],['03','Получите актуальные данные','Расписание и изменения приходят в одном потоке.'],['04','Работайте без лишних переходов','Пары, материалы, группы и системные действия рядом.']].map(([number,title,description]) => <div key={number}><span className="text-4xl font-extrabold text-indigo-100">{number}</span><h3 className="mt-2 font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>)}</div></div></section>
    <footer className="border-t border-slate-200 bg-white px-4 py-10 sm:px-6"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-slate-500 sm:flex-row"><span className="font-semibold text-slate-900">НаПаре</span><span>Цифровая платформа университета · © 2026</span><a href="mailto:support@napare.ru" className="hover:text-slate-900">support@napare.ru</a></div></footer>
  </main>;
}
