'use client';

import Link from 'next/link';
import { useState } from 'react';

export function PublicNavigation() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/90 py-2 text-white backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-2.5 text-lg font-bold" aria-label="NaPare, на главную"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-400 text-sm font-bold text-slate-950">Н</span>NaPare Developer</Link><nav className="hidden xl:flex"><Link href="/" className="rounded-lg px-3 py-2 text-sm text-white/60 hover:bg-white/10 hover:text-white">О платформе</Link></nav><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-semibold hover:bg-white/10 sm:block">Войти</Link><button type="button" onClick={() => setOpen(true)} className="h-11 w-11 rounded-lg text-xl hover:bg-white/10 xl:hidden" aria-label="Открыть меню">☰</button></div>{open && <div className="fixed inset-0 z-50 bg-slate-950 p-5"><div className="flex items-center justify-between"><Link href="/" className="text-lg font-bold" onClick={() => setOpen(false)}>NaPare Developer</Link><button type="button" onClick={() => setOpen(false)} className="h-11 w-11 rounded-lg text-2xl hover:bg-white/10" aria-label="Закрыть меню">×</button></div><nav className="mt-8"><Link href="/" onClick={() => setOpen(false)} className="block rounded-xl px-4 py-3 text-lg text-white/80 hover:bg-white/10">О платформе</Link></nav><div className="absolute inset-x-5 bottom-6 border-t border-white/10 pt-5"><Link href="/login" onClick={() => setOpen(false)} className="block rounded-xl bg-cyan-400 px-4 py-3 text-center font-semibold text-slate-950">Войти</Link></div></div>}</header>;
}

export function PublicFooter() { return <footer className="border-t border-white/10 bg-slate-950 px-6 py-10 text-slate-400"><div className="mx-auto grid max-w-7xl gap-8 text-sm sm:grid-cols-3"><div><div className="flex items-center gap-2 font-bold text-white"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-400 text-slate-950">Н</span>NaPare Developer</div><p className="mt-3">Developer portal университетской платформы</p></div><div><h2 className="font-semibold text-white">Продукт</h2><Link href="/" className="mt-3 block hover:text-white">О платформе</Link><Link href="/login" className="mt-2 block hover:text-white">Войти в портал</Link></div><div><h2 className="font-semibold text-white">Поддержка</h2><a href="mailto:support@napare.ru" className="mt-3 block hover:text-white">support@napare.ru</a><p className="mt-5 text-xs text-slate-500">© 2026 NaPare</p></div></div></footer>; }
