'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { Badge, Button, Card, EmptyState, RequestState, Skeleton } from '@/components/ui';

type Step = 1 | 2 | 3 | 4 | 5 | 6 | 7;
interface PreviewRow { date: string; time: string; subject: string; teacher: string; group: string; room: string; }
interface HistoryItem { id: string; date: string; file: string; status: string; imported: number; }
const steps = ['Upload', 'Detect', 'Map', 'Validate', 'Preview', 'Apply', 'Sync'];
const fields = ['Дата', 'Время', 'Предмет', 'Преподаватель', 'Группа', 'Аудитория'];
const ext = (file: File) => file.name.split('.').pop()?.toLowerCase() || '';
const parseCsv = (value: string): PreviewRow[] => value.split(/\r?\n/).filter(Boolean).slice(1).map((line) => line.split(/[;,]/).map((item) => item.trim())).map((row) => ({ date: row[0] || '—', time: row[1] || '—', subject: row[2] || '—', teacher: row[3] || '—', group: row[4] || '—', room: row[5] || '—' })).slice(0, 100);
const parseJson = (value: string): PreviewRow[] => { const parsed = JSON.parse(value); const source = Array.isArray(parsed) ? parsed : parsed.lessons; return Array.isArray(source) ? source.slice(0, 100).map((row) => ({ date: String(row.date || row.startDate || '—'), time: String(row.time || row.startTime || '—'), subject: String(row.subject || row.title || '—'), teacher: String(row.teacher || row.teacherName || '—'), group: String(row.group || row.groupName || '—'), room: String(row.room || '—') })) : []; };

export default function ScheduleImportPage() {
  const [step, setStep] = useState<Step>(1); const [file, setFile] = useState<File | null>(null); const [rows, setRows] = useState<PreviewRow[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({ date: 'Дата', time: 'Время', subject: 'Предмет', teacher: 'Преподаватель', group: 'Группа', room: 'Аудитория' }); const [validation, setValidation] = useState({ conflicts: 0, ambiguous: 0, errors: 0 }); const [history, setHistory] = useState<HistoryItem[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { try { setHistory(JSON.parse(localStorage.getItem('napare:import-history') || '[]')); } catch { setHistory([]); } }, []);
  const chooseFile = useCallback(async (selected: File) => { if (!['csv', 'xlsx', 'xls', 'json'].includes(ext(selected))) { setError('Поддерживаются CSV, Excel и JSON.'); return; } setError(''); setMessage(''); setFile(selected); setStep(2); try { const text = await selected.text(); const parsed = ext(selected) === 'csv' ? parseCsv(text) : ext(selected) === 'json' ? parseJson(text) : []; setRows(parsed); } catch { setRows([]); setError('Не удалось прочитать файл. Для Excel нужен server-side detector.'); } }, []);
  const validate = () => { const slots = new Set<string>(); let conflicts = 0; let ambiguous = 0; rows.forEach((row) => { const slot = `${row.date}|${row.time}|${row.room}`; if (row.room !== '—' && slots.has(slot)) conflicts += 1; slots.add(slot); if (row.teacher === '—' || row.group === '—' || row.subject === '—') ambiguous += 1; }); setValidation({ conflicts, ambiguous, errors: rows.length ? 0 : 1 }); setStep(4); };
  const apply = async () => { if (!file || validation.errors || validation.conflicts) return; setLoading(true); setError(''); setStep(6); try { const result = await apiFetch<{ imported?: number }>('/admin/schedule/upload', { method: 'POST', body: JSON.stringify({ fileName: file.name, format: ext(file) }) }); const item = { id: String(Date.now()), date: new Date().toISOString(), file: file.name, status: 'Применён', imported: result.imported || rows.length }; const next = [item, ...history].slice(0, 10); setHistory(next); localStorage.setItem('napare:import-history', JSON.stringify(next)); setStep(7); await apiFetch('/admin/schedule/sync', { method: 'POST' }); setMessage('Изменения применены и синхронизация запущена.'); } catch (err) { setError(err instanceof Error ? err.message : 'Изменения не применены.'); setStep(6); } finally { setLoading(false); } };
  const reset = () => { setStep(1); setFile(null); setRows([]); setValidation({ conflicts: 0, ambiguous: 0, errors: 0 }); setError(''); setMessage(''); };
  const groups = new Set(rows.map((row) => row.group).filter((value) => value !== '—')).size; const teachers = new Set(rows.map((row) => row.teacher).filter((value) => value !== '—')).size; const rooms = new Set(rows.map((row) => row.room).filter((value) => value !== '—')).size;
  return <div className="mx-auto max-w-[1250px] space-y-6"><div><p className="text-sm font-medium text-sky-700">Schedule Operations</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Импорт расписания</h1><p className="mt-1 text-sm text-slate-500">Безопасный pipeline от обнаружения записей до синхронизации.</p></div><div className="grid grid-cols-7 gap-1 sm:gap-3">{steps.map((label, index) => <div key={label} className={`border-t-2 px-1 pt-2 sm:px-0 ${step >= index + 1 ? 'border-sky-600' : 'border-slate-200'}`}><p className={`text-[10px] font-bold uppercase tracking-wide sm:text-xs ${step >= index + 1 ? 'text-sky-700' : 'text-slate-400'}`}>{index + 1} <span className="hidden sm:inline">{label}</span></p></div>)}</div>{error && <RequestState title="Pipeline остановлен" description={error} onRetry={() => setError('')} />}{message && <p role="status" className="rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-800">{message}</p>}
    {step === 1 && <Card className="border-dashed border-2 px-5 py-12 text-center"><input id="schedule-file" type="file" accept=".csv,.xlsx,.xls,.json" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) void chooseFile(selected); }} className="sr-only" /><label htmlFor="schedule-file" className="cursor-pointer"><p className="text-base font-semibold text-slate-900">Загрузить файл расписания</p><p className="mt-2 text-sm text-slate-500">CSV, Excel или JSON. До применения будет показан diff.</p></label></Card>}
    {step === 2 && <Card padding="sm"><h2 className="font-bold text-slate-950">Detect</h2><p className="mt-1 text-sm text-slate-500">{file?.name} · {file ? (file.size / 1024).toFixed(1) : 0} KB</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: 'Занятия', value: rows.length }, { label: 'Группы', value: groups }, { label: 'Преподаватели', value: teachers }, { label: 'Аудитории', value: rooms }].map((item) => <div key={item.label} className="rounded-xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{item.label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{item.value}</p></div>)}</div><Button className="mt-5" onClick={() => setStep(3)} disabled={!rows.length}>Перейти к mapping</Button></Card>}
    {step === 3 && <Card padding="sm"><h2 className="font-bold text-slate-950">Map fields</h2><p className="mt-1 text-sm text-slate-500">Проверьте, как поля источника попадут в расписание.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(mapping).map(([key, value]) => <label key={key} className="text-sm font-medium text-slate-700">{key}<select value={value} onChange={(event) => setMapping((current) => ({ ...current, [key]: event.target.value }))} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100">{fields.map((field) => <option key={field}>{field}</option>)}</select></label>)}</div><Button className="mt-5" onClick={validate}>Validate</Button></Card>}
    {step === 4 && <Card padding="sm"><h2 className="font-bold text-slate-950">Validate</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase text-emerald-700">Valid rows</p><p className="mt-2 text-2xl font-bold text-emerald-900">{rows.length - validation.ambiguous}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-700">Ambiguous</p><p className="mt-2 text-2xl font-bold text-amber-900">{validation.ambiguous}</p></div><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-xs font-semibold uppercase text-red-700">Conflicts</p><p className="mt-2 text-2xl font-bold text-red-900">{validation.conflicts}</p></div></div><Button className="mt-5" onClick={() => setStep(5)} disabled={validation.errors > 0 || validation.conflicts > 0}>Open preview</Button></Card>}
    {step === 5 && <Card padding="sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-950">Preview / Diff</h2><p className="mt-1 text-sm text-slate-500">Added: {rows.length} · Changed: 0 · Removed: 0 · Conflicts: {validation.conflicts}</p></div><Badge variant={validation.conflicts ? 'red' : 'green'}>{validation.conflicts ? 'Blocked' : 'Ready'}</Badge></div>{rows.length ? <div className="mt-4 max-h-[420px] overflow-auto rounded-xl border border-slate-200"><table className="min-w-[800px] w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{fields.map((field) => <th key={field} className="px-3 py-3">{field}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={index}><td className="px-3 py-3">{row.date}</td><td className="px-3 py-3">{row.time}</td><td className="px-3 py-3 font-medium">{row.subject}</td><td className="px-3 py-3">{row.teacher}</td><td className="px-3 py-3">{row.group}</td><td className="px-3 py-3">{row.room}</td></tr>)}</tbody></table></div> : <EmptyState title="Нет preview rows" description="Server-side detector не вернул строки для этого формата." />}<Button className="mt-5" onClick={() => setStep(6)} disabled={validation.conflicts > 0}>Перейти к apply</Button></Card>}
    {step === 6 && <Card padding="sm" className="border-amber-200"><h2 className="font-bold text-slate-950">Apply changes</h2><p className="mt-2 text-sm leading-6 text-slate-600">Будут применены только записи из preview. Конфликты блокируют pipeline. После подтверждения запустится отдельная sync-операция.</p><div className="mt-5 flex gap-2"><Button variant="secondary" onClick={() => setStep(5)}>Вернуться к preview</Button><Button loading={loading} onClick={apply}>Подтвердить и применить</Button></div></Card>}
    {step === 7 && <Card padding="sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-950">Sync complete</h2><p className="mt-1 text-sm text-slate-500">Изменения применены, синхронизация запущена.</p></div><Badge variant="green">Synced</Badge></div><Button variant="secondary" className="mt-5" onClick={reset}>Новый импорт</Button></Card>}
    <Card padding="sm"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><h2 className="font-bold text-slate-950">История запусков</h2><span className="text-xs text-slate-400">{history.length} записей</span></div>{history.length ? <div className="divide-y divide-slate-100">{history.map((item) => <div key={item.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-900">{item.file}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.date).toLocaleString('ru-RU')} · {item.imported} записей</p></div><Badge variant={item.status === 'Применён' ? 'green' : 'red'}>{item.status}</Badge></div>)}</div> : <p className="py-4 text-sm text-slate-500">История пока пуста.</p>}</Card>
  </div>;
}
