'use client';

import { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode, forwardRef, useEffect, useState, createContext, useContext, useCallback } from 'react';

const cn = (...values: Array<string | number | false | null | undefined>) => values.filter(Boolean).join(' ');

import { Icon } from './icons';
export { Icon };
export type { IconName } from './icons';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: 'primary' | 'secondary' | 'danger' | 'ghost'; size?: 'sm' | 'md' | 'lg'; loading?: boolean; fullWidth?: boolean; }
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ children, variant = 'primary', size = 'md', loading = false, fullWidth = false, disabled, className = '', ...props }, ref) {
  const styles = { primary: 'bg-[var(--color-brand)] text-white hover:bg-[var(--color-brand-strong)]', secondary: 'border bg-[var(--color-surface)] text-[var(--color-text)] hover:bg-[var(--color-surface-secondary)]', danger: 'bg-[var(--color-danger)] text-white hover:brightness-95', ghost: 'text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-secondary)] hover:text-[var(--color-text)]' };
  const sizes = { sm: 'min-h-9 rounded-[var(--radius-sm)] px-3 text-xs', md: 'min-h-11 rounded-[var(--radius-md)] px-4 text-sm', lg: 'min-h-12 rounded-[var(--radius-md)] px-5 text-sm' };
  return <button ref={ref} disabled={disabled || loading} className={cn('inline-flex items-center justify-center gap-2 font-semibold transition-[background-color,border-color,box-shadow,transform] duration-[var(--motion-fast)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-brand-soft)] disabled:pointer-events-none disabled:opacity-50', styles[variant], sizes[size], fullWidth && 'w-full', className)} {...props}>{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-r-transparent" aria-label="Загрузка" />}{children}</button>;
});

export type BadgeVariant = 'sky' | 'green' | 'amber' | 'red' | 'purple' | 'slate' | 'pink' | 'teal' | 'indigo' | 'default' | 'success' | 'warning' | 'danger' | 'info';
export function Badge({ children, variant = 'slate', size = 'sm', dot = false, className = '', ...props }: HTMLAttributes<HTMLSpanElement> & { variant?: BadgeVariant; size?: 'sm' | 'md'; dot?: boolean }) {
  const key = variant === 'default' ? 'slate' : variant === 'success' ? 'green' : variant === 'warning' ? 'amber' : variant === 'danger' ? 'red' : variant === 'info' ? 'sky' : variant;
  const styles: Record<string, string> = { sky: 'bg-[var(--color-info-soft)] text-[var(--color-info)]', green: 'bg-[var(--color-success-soft)] text-[var(--color-success)]', amber: 'bg-[var(--color-warning-soft)] text-[var(--color-warning)]', red: 'bg-[var(--color-danger-soft)] text-[var(--color-danger)]', purple: 'bg-violet-50 text-violet-700', slate: 'bg-[var(--color-surface-secondary)] text-[var(--color-text-secondary)]', pink: 'bg-pink-50 text-pink-700', teal: 'bg-teal-50 text-teal-700', indigo: 'bg-indigo-50 text-indigo-700' };
  return <span className={cn('inline-flex items-center gap-1.5 rounded-full font-medium', size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-2.5 py-1 text-xs', styles[key], className)} {...props}>{dot && <span className="h-1.5 w-1.5 rounded-full bg-current" />}{children}</span>;
}

interface CardProps extends HTMLAttributes<HTMLDivElement> { hover?: boolean; padding?: 'sm' | 'md' | 'lg'; variant?: 'default' | 'hover' | 'bordered'; }
export const Card = forwardRef<HTMLDivElement, CardProps>(function Card({ children, className = '', hover = false, padding = 'md', variant = 'default', ...props }, ref) { return <div ref={ref} className={cn('ds-card', padding === 'sm' ? 'p-4' : padding === 'lg' ? 'p-8' : 'p-6', (hover || variant === 'hover') && 'cursor-pointer transition-[border-color,box-shadow,transform] duration-[var(--motion-fast)] hover:-translate-y-px hover:border-[var(--color-brand)] hover:shadow-[var(--shadow-md)]', className)} {...props}>{children}</div>; });

interface InputProps extends InputHTMLAttributes<HTMLInputElement> { label?: string; error?: string; icon?: ReactNode; }
export const Input = forwardRef<HTMLInputElement, InputProps>(function Input({ label, error, icon, id, className = '', ...props }, ref) { const inputId = id || (label ? `input-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined); return <div className="w-full">{label && <label htmlFor={inputId} className="mb-1.5 block text-sm font-medium text-[var(--color-text)]">{label}</label>}<div className="relative">{icon && <span className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3 text-[var(--color-text-muted)]">{icon}</span>}<input ref={ref} id={inputId} aria-invalid={Boolean(error)} aria-describedby={error ? `${inputId}-error` : undefined} className={cn('ds-input block min-h-11 w-full px-3.5 py-2.5 text-sm placeholder:text-[var(--color-text-muted)] transition-[border-color,box-shadow,background-color] duration-[var(--motion-fast)] focus:border-[var(--color-brand)] focus:bg-[var(--color-surface)] focus:outline-none focus:ring-4 focus:ring-[var(--color-brand-soft)]', Boolean(icon) && 'pl-10', error && 'border-[var(--color-danger)] focus:border-[var(--color-danger)] focus:ring-[var(--color-danger-soft)]', className)} {...props} /></div>{error && <p id={`${inputId}-error`} className="mt-1 text-xs text-[var(--color-danger)]">{error}</p>}</div>; });

export function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title?: string; children: ReactNode }) { useEffect(() => { document.body.style.overflow = open ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [open]); if (!open) return null; return <div className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center p-3 sm:p-4" role="presentation"><button type="button" className="absolute inset-0 cursor-default bg-slate-950/35 backdrop-blur-[2px]" aria-label="Закрыть окно" onClick={onClose} /><div role="dialog" aria-modal="true" aria-labelledby={title ? 'dialog-title' : undefined} className="ds-modal relative max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-[var(--radius-xl)] bg-[var(--color-surface)] p-4 shadow-[var(--shadow-lg)] sm:max-h-[calc(100dvh-2rem)] sm:p-6">{title && <div className="mb-5 flex items-center justify-between gap-4"><h3 id="dialog-title" className="ds-section-title">{title}</h3><button type="button" onClick={onClose} className="inline-flex h-11 w-11 items-center justify-center rounded-[var(--radius-md)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-secondary)]" aria-label="Закрыть окно"><Icon name="close" /></button></div>}{children}</div></div>; }
export function ConfirmDialog({ open, title, description, confirmLabel = 'Удалить', loading = false, onConfirm, onClose }: { open: boolean; title: string; description: string; confirmLabel?: string; loading?: boolean; onConfirm: () => void; onClose: () => void }) { return <Modal open={open} onClose={onClose} title={title}><p className="text-sm leading-6 text-[var(--color-text-secondary)]">{description}</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose} disabled={loading}>Отмена</Button><Button variant="danger" onClick={onConfirm} loading={loading}>{confirmLabel}</Button></div></Modal>; }

export function EmptyState({ icon, title, description, action }: { icon?: ReactNode; title: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-[220px] flex-col items-center justify-center px-5 py-12 text-center">{icon && <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-[var(--radius-lg)] bg-[var(--color-surface-secondary)] text-[var(--color-text-secondary)]">{icon}</div>}<h3 className="ds-card-title">{title}</h3>{description && <p className="mt-2 max-w-sm text-sm leading-6 text-[var(--color-text-secondary)]">{description}</p>}{action && <div className="mt-6">{action}</div>}</div>; }
export function Skeleton({ className = '', lines = 1, count }: { className?: string; lines?: number; count?: number }) { const total = count ?? lines; return total > 1 ? <div className={cn('space-y-2', className)}>{Array.from({ length: total }).map((_, i) => <div key={i} className="h-4 animate-pulse rounded-[var(--radius-sm)] bg-[var(--color-surface-tertiary)]" style={{ width: `${88 - i * 9}%` }} />)}</div> : <div className={cn('animate-pulse rounded-[var(--radius-md)] bg-[var(--color-surface-tertiary)]', className)} />; }
export function StatCard({ label, value, icon }: { label: string; value: string | number; icon?: ReactNode; gradient?: string }) { return <div className="ds-card flex items-center justify-between gap-4 p-5"><div><p className="text-2xl font-bold tracking-tight text-[var(--color-text)]">{value}</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{label}</p></div>{icon && <div className="flex h-10 w-10 items-center justify-center rounded-[var(--radius-md)] bg-[var(--color-brand-soft)] text-[var(--color-brand)]">{icon}</div>}</div>; }
export function TabBar({ tabs, activeTab, onChange }: { tabs: Array<{ id: string; label: string; icon?: ReactNode; count?: number }>; activeTab: string; onChange: (id: string) => void }) { return <div className="overflow-x-auto border-b border-[var(--color-border)]" aria-label="Вкладки"><div className="flex min-w-max gap-1">{tabs.map(tab => <button type="button" key={tab.id} onClick={() => onChange(tab.id)} aria-selected={activeTab === tab.id} className={cn('flex min-h-11 shrink-0 items-center justify-center gap-1.5 border-b-2 px-3 py-2 text-sm font-medium transition-colors', activeTab === tab.id ? 'border-[var(--color-brand)] text-[var(--color-brand)]' : 'border-transparent text-[var(--color-text-secondary)] hover:border-[var(--color-border-strong)] hover:text-[var(--color-text)]')}>{tab.icon}{tab.label}{tab.count !== undefined && <span className="rounded-full bg-[var(--color-surface-secondary)] px-1.5 py-0.5 text-xs">{tab.count}</span>}</button>)}</div></div>; }
export function SearchInput({ onSearch, onChange, className = '', ...props }: InputHTMLAttributes<HTMLInputElement> & { onSearch?: (value: string) => void }) { return <div className={cn('relative', className)}><Icon name="search" className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" size={17} /><input type="search" {...props} onChange={event => { onChange?.(event); onSearch?.(event.target.value); }} className="ds-input block min-h-11 w-full py-2.5 pl-10 pr-3.5 text-sm placeholder:text-[var(--color-text-muted)] focus:border-[var(--color-brand)] focus:outline-none focus:ring-4 focus:ring-[var(--color-brand-soft)]" /></div>; }
export function RequestState({ kind = 'error', title, description, onRetry, action }: { kind?: 'error' | 'forbidden' | 'offline'; title: string; description: string; onRetry?: () => void; action?: ReactNode }) { const icon = kind === 'forbidden' ? 'warning' : kind === 'offline' ? 'info' : 'error'; const tone = kind === 'forbidden' ? 'bg-[var(--color-warning-soft)] text-[var(--color-warning)]' : kind === 'offline' ? 'bg-[var(--color-surface-secondary)] text-[var(--color-text-secondary)]' : 'bg-[var(--color-danger-soft)] text-[var(--color-danger)]'; return <div className="flex min-h-[240px] flex-col items-center justify-center px-5 py-12 text-center"><div className={cn('flex h-12 w-12 items-center justify-center rounded-[var(--radius-lg)]', tone)}><Icon name={icon} /></div><h3 className="mt-4 ds-card-title">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[var(--color-text-secondary)]">{description}</p><div className="mt-6 flex flex-wrap justify-center gap-3">{onRetry && <Button onClick={onRetry}>Повторить</Button>}{action}</div></div>; }
export function NetworkStatus() { const [online, setOnline] = useState(true); useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener('online', update); window.addEventListener('offline', update); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update); }; }, []); if (online) return null; return <div role="status" className="fixed inset-x-0 bottom-4 z-[var(--z-toast)] mx-auto flex w-fit max-w-[calc(100%-2rem)] items-center gap-3 rounded-[var(--radius-md)] bg-slate-900 px-4 py-3 text-sm text-white shadow-[var(--shadow-lg)]"><span>Нет подключения к сети. Проверьте интернет и повторите попытку.</span><button type="button" onClick={() => window.location.reload()} className="shrink-0 font-semibold text-indigo-200 hover:text-white">Обновить</button></div>; }
export function Avatar({ name, size = 'md', className = '' }: { name: string; size?: 'sm' | 'md' | 'lg'; className?: string }) { const initials = name.split(' ').map(word => word[0]).join('').toUpperCase().slice(0, 2); return <div aria-label={name} className={cn('inline-flex items-center justify-center rounded-full bg-[var(--color-brand-soft)] font-semibold text-[var(--color-brand)]', size === 'sm' ? 'h-8 w-8 text-xs' : size === 'lg' ? 'h-14 w-14 text-lg' : 'h-10 w-10 text-sm', className)}>{initials}</div>; }

export function ToastProvider({ children }: { children: ReactNode }) { const [toasts, setToasts] = useState<Array<{ id: number; message: string; type: 'success' | 'error' | 'info' }>>([]); const toast = useCallback((message: string, type: 'success' | 'error' | 'info' = 'info') => setToasts(prev => [...prev, { id: Date.now() + Math.random(), message, type }]), []); useEffect(() => { if (!toasts.length) return; const timer = setTimeout(() => setToasts(prev => prev.slice(1)), 3000); return () => clearTimeout(timer); }, [toasts]); return <ToastContext.Provider value={{ toast }}>{children}<div className="fixed bottom-4 right-4 z-[var(--z-toast)] flex max-w-[calc(100%-2rem)] flex-col gap-2">{toasts.map(item => <button type="button" key={item.id} onClick={() => setToasts(prev => prev.filter(t => t.id !== item.id))} className={cn('ds-notification rounded-[var(--radius-md)] px-4 py-3 text-left text-sm font-medium text-white shadow-[var(--shadow-md)]', item.type === 'success' ? 'bg-[var(--color-success)]' : item.type === 'error' ? 'bg-[var(--color-danger)]' : 'bg-[var(--color-text)]')}>{item.message}</button>)}</div></ToastContext.Provider>; }
const ToastContext = createContext<{ toast: (message: string, type?: 'success' | 'error' | 'info') => void }>({ toast: () => undefined });
export const useToast = () => useContext(ToastContext);


export default Button;
