'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { apiFetch, apiFetchList } from '@/lib/api';
import { Badge, Button, Card, EmptyState, RequestState, Skeleton } from '@/components/ui';

interface AdminUser { id: string; firstName: string; lastName: string; role?: string; lastLoginAt?: string; isActive?: boolean; }
interface Group { id: string; name: string; }
interface Faculty { id: string; name: string; }
interface Lesson { id: string; startTime?: string; endTime?: string; subject?: string; groupName?: string; room?: string; teacherName?: string; isChanged?: boolean; changeDescription?: string; }
interface Notice { id?: string; title?: string; body?: string; type?: string; createdAt?: string; isRead?: boolean; }
interface Sync { status?: string; lastSync?: string | null; }

const dateKey = (value: Date) => value.toISOString().split('T')[0];
const role = (user: AdminUser) => user.role || 'student';
const displayNumber = (value: number) => new Intl.NumberFormat('ru-RU').format(value);
const time = (value?: string) => value?.includes('T') ? value.slice(11, 16) : value || '—';

function sameSlot(a: Lesson, b: Lesson) { return Boolean(a.startTime && b.startTime && time(a.startTime) === time(b.startTime) && a.room && b.room && a.room === b.room); }

export default function DashboardPage() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [faculties, setFaculties] = useState<Faculty[]>([]); const [lessons, setLessons] = useState<Lesson[]>([]); const [notices, setNotices] = useState<Notice[]>([]); const [sync, setSync] = useState<Sync | null>(null); const [backend, setBackend] = useState<'online' | 'offline' | 'unknown'>('unknown'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); const today = dateKey(new Date()); Promise.all([apiFetchList<AdminUser>('/admin/users?limit=100'), apiFetchList<Group>('/admin/groups?limit=100'), apiFetchList<Faculty>('/admin/faculties?limit=100'), apiFetchList<Lesson>(`/schedule?date=${today}&limit=100`).catch(() => []), apiFetchList<Notice>('/notifications').catch(() => []), apiFetch<Sync>('/admin/schedule/sync-status').catch(() => null), apiFetch<{ status: string }>('/health').then(() => 'online' as const).catch(() => 'offline' as const)]).then(([userItems, groupItems, facultyItems, lessonItems, notificationItems, syncStatus, health]) => { setUsers(userItems); setGroups(groupItems); setFaculties(facultyItems); setLessons(lessonItems); setNotices(notificationItems); setSync(syncStatus); setBackend(health); }).catch((err) => setError(err instanceof Error ? err.message : 'Не удалось загрузить операционную сводку.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const today = dateKey(new Date()); const students = users.filter((user) => role(user) === 'student').length; const teachers = users.filter((user) => role(user) === 'teacher').length; const activeToday = users.filter((user) => user.lastLoginAt?.slice(0, 10) === today).length; const unread = notices.filter((notice) => notice.isRead === false).length;
  const problems = useMemo(() => { const missingRooms = lessons.filter((lesson) => !lesson.room).length; const conflicts = lessons.filter((lesson, index) => lessons.some((other, otherIndex) => otherIndex > index && sameSlot(lesson, other))).length; const unmappedTeachers = lessons.filter((lesson) => !lesson.teacherName).length; const importErrors = notices.filter((notice) => (notice.type || '').toLowerCase().includes('import') || (notice.type || '').toLowerCase().includes('error')).length; return [{ label: 'Занятия без аудитории', value: missingRooms, href: '/schedule-import', description: 'Нужно проверить назначение помещений' }, { label: 'Конфликты расписания', value: conflicts, href: '/schedule-import', description: 'Совпадающие временные слоты и аудитории' }, { label: 'Преподаватели не сопоставлены', value: unmappedTeachers, href: '/users?role=teacher', description: 'В расписании отсутствует связь с аккаунтом' }, { label: 'Ошибки импорта', value: importErrors, href: '/schedule-import', description: 'События импорта из системных уведомлений' }]; }, [lessons, notices]);
  const openProblems = problems.filter((item) => item.value > 0).reduce((sum, item) => sum + item.value, 0); const pendingActions = openProblems + unread + (sync?.status === 'error' ? 1 : 0); const syncLabel = sync?.status === 'error' ? 'Ошибка' : sync?.status === 'synced' || sync?.status === 'active' ? 'Синхронизировано' : 'Нет данных';
  if (loading) return <div className="mx-auto max-w-[1500px] space-y-6"><Skeleton className="h-24" /><Skeleton className="h-44" /><Skeleton className="h-[380px]" /></div>;
  if (error && !users.length) return <div className="mx-auto max-w-[1500px]"><RequestState title="Не удалось загрузить Operations Center" description={error} onRetry={load} /></div>;
  return <div className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">University Operations Center</h1><p className="mt-1 text-sm text-slate-500">{new Date().toLocaleDateString('ru-RU', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })} · контроль состояния университета</p></div><div className="flex gap-2"><Badge variant={backend === 'online' ? 'green' : backend === 'offline' ? 'red' : 'slate'} dot>{backend === 'online' ? 'Backend online' : backend === 'offline' ? 'Backend error' : 'Checking'}</Badge><Link href="/schedule-import"><Button size="sm">Импортировать данные</Button></Link></div></div>
    {error && <p className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">Часть operational data недоступна: {error}</p>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><Card className="border-red-200" padding="sm"><div className="flex items-center justify-between border-b border-red-100 pb-3"><div><h2 className="text-lg font-bold text-slate-950">Problems / Attention Required</h2><p className="mt-1 text-sm text-slate-500">Данные рассчитаны по текущему расписанию и системным событиям</p></div><Badge variant={openProblems ? 'red' : 'green'}>{openProblems || 'OK'}</Badge></div><div className="divide-y divide-slate-100">{problems.map((problem) => <Link key={problem.label} href={problem.href} className="flex items-center justify-between gap-4 py-4 hover:bg-slate-50"><div><p className="text-sm font-semibold text-slate-900">{problem.label}</p><p className="mt-1 text-xs text-slate-500">{problem.description}</p></div><span className={`text-lg font-bold ${problem.value ? 'text-red-600' : 'text-slate-400'}`}>{problem.value}</span></Link>)}</div></Card><Card padding="sm"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><h2 className="text-lg font-bold text-slate-950">System status</h2><Badge variant={sync?.status === 'error' ? 'red' : sync ? 'green' : 'slate'} dot>{syncLabel}</Badge></div><div className="divide-y divide-slate-100"><div className="flex items-center justify-between py-3 text-sm"><span className="text-slate-600">Backend</span><span className={backend === 'online' ? 'text-emerald-700' : 'text-red-700'}>{backend === 'online' ? 'Работает' : 'Ошибка'}</span></div><div className="flex items-center justify-between py-3 text-sm"><span className="text-slate-600">Schedule sync</span><span className="text-slate-700">{syncLabel}</span></div><div className="flex items-center justify-between py-3 text-sm"><span className="text-slate-600">Последняя sync</span><span className="text-right text-xs text-slate-500">{sync?.lastSync ? new Date(sync.lastSync).toLocaleString('ru-RU') : 'Нет данных'}</span></div></div><Link href="/connectors" className="mt-4 block text-sm font-semibold text-sky-700">Открыть Connector Center</Link></Card></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{[{ label: 'Пользователи', value: users.length, href: '/users' }, { label: 'Активные сегодня', value: activeToday, href: '/users?status=active' }, { label: 'Студенты', value: students, href: '/users?role=student' }, { label: 'Преподаватели', value: teachers, href: '/users?role=teacher' }, { label: 'Группы', value: groups.length, href: '/groups' }, { label: 'Факультеты', value: faculties.length, href: '/faculties' }, { label: 'Занятия сегодня', value: lessons.length, href: '/schedule-import' }, { label: 'Pending actions', value: pendingActions, href: '/notifications' }].map((metric) => <Link key={metric.label} href={metric.href} className="min-w-0"><Card hover padding="sm" className="h-full"><p className="truncate text-xs font-medium text-slate-500">{metric.label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{displayNumber(metric.value)}</p></Card></Link>)}</div>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><Card padding="sm"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><div><h2 className="text-lg font-bold text-slate-950">Сегодня в расписании</h2><p className="mt-1 text-sm text-slate-500">{lessons.length} записей · изменения отмечены отдельно</p></div><Link href="/schedule-import" className="text-sm font-semibold text-sky-700">Открыть schedule</Link></div>{lessons.length ? <div className="mt-2 divide-y divide-slate-100">{lessons.slice(0, 8).map((lesson) => <div key={lesson.id} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{lesson.subject || 'Без названия'}</p><p className="mt-1 text-xs text-slate-500">{time(lesson.startTime)}–{time(lesson.endTime)} · {lesson.groupName || 'Группа не указана'} · ауд. {lesson.room || 'не назначена'}</p></div>{lesson.isChanged ? <Badge variant="amber">Изменено</Badge> : <Badge variant="slate">По плану</Badge>}</div>)}</div> : <div className="py-6"><EmptyState title="Нет занятий на сегодня" description="Проверьте импорт расписания или выбранную дату." /></div>}</Card><div className="space-y-6"><Card padding="sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Pending actions</h2><span className="text-xs text-slate-400">{pendingActions}</span></div><div className="mt-3 divide-y divide-slate-100"><Link href="/notifications" className="flex justify-between py-3 text-sm"><span className="text-slate-600">Непрочитанные события</span><b className="text-slate-900">{unread}</b></Link><Link href="/schedule-import" className="flex justify-between py-3 text-sm"><span className="text-slate-600">Проблемы расписания</span><b className="text-slate-900">{openProblems}</b></Link></div></Card><Card padding="sm"><h2 className="font-bold text-slate-950">Quick actions</h2><div className="mt-3 space-y-2"><Link href="/users"><Button variant="secondary" fullWidth>Открыть пользователей</Button></Link><Link href="/university"><Button variant="secondary" fullWidth>Проверить структуру</Button></Link><Link href="/audit-log"><Button variant="secondary" fullWidth>Открыть Audit Log</Button></Link></div></Card></div></div>
  </div>;
}
