'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const links = [['#showcase', 'Возможности'], ['#how-it-works', 'Как это работает'], ['#students', 'Для студентов'], ['#teachers', 'Для преподавателей'], ['#universities', 'Для университетов'], ['#about', 'О платформе']];

export function PublicNavigation() {
  const [compact, setCompact] = useState(false);
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState('#showcase');
  useEffect(() => { const onScroll = () => { setCompact(window.scrollY > 24); const current = links.map(([href]) => href).reverse().find((href) => { const element = document.querySelector(href); return element && element.getBoundingClientRect().top <= 140; }); if (current) setActive(current); }; window.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => window.removeEventListener('scroll', onScroll); }, []);
  const close = () => setOpen(false);
  return <header className={`sticky top-0 z-50 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl transition-all ${compact ? 'py-1 shadow-sm' : 'py-2'}`}><div className="mx-auto flex max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2.5 rounded-lg p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500" aria-label="НаПаре, на главную"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600 text-sm font-bold text-white">Н</span><span className="text-lg font-bold tracking-tight text-slate-900">НаПаре</span></Link><nav className="hidden items-center gap-1 xl:flex" aria-label="Основная навигация">{links.map(([href, label]) => <a key={href} href={href} aria-current={active === href ? 'location' : undefined} className={`rounded-lg px-3 py-2 text-sm font-medium transition ${active === href ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'} focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500`}>{label}</a>)}</nav><div className="hidden items-center gap-2 sm:flex"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">Войти</Link><Link href="/register" className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">Зарегистрироваться</Link></div><button type="button" onClick={() => setOpen(true)} className="flex h-11 w-11 items-center justify-center rounded-lg text-slate-700 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 xl:hidden" aria-label="Открыть меню"><span className="text-xl" aria-hidden="true">☰</span></button></div>{open && <div className="fixed inset-0 z-50 bg-white p-5 xl:hidden"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-lg font-bold text-slate-900" onClick={close}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600 text-sm text-white">Н</span>НаПаре</Link><button type="button" onClick={close} className="h-11 w-11 rounded-lg text-2xl hover:bg-slate-100" aria-label="Закрыть меню">×</button></div><nav className="mt-8 grid gap-2" aria-label="Мобильная навигация">{links.map(([href, label]) => <a key={href} href={href} onClick={close} aria-current={active === href ? 'location' : undefined} className="rounded-xl px-4 py-3 text-lg font-medium text-slate-700 hover:bg-slate-100">{label}</a>)}</nav><div className="absolute inset-x-5 bottom-6 grid gap-2 border-t border-slate-200 pt-5"><Link href="/login" onClick={close} className="rounded-xl px-4 py-3 text-center font-semibold text-slate-700 hover:bg-slate-100">Войти</Link><Link href="/register" onClick={close} className="rounded-xl bg-indigo-600 px-4 py-3 text-center font-semibold text-white">Зарегистрироваться</Link></div></div>}</header>;
}

const footerColumns: Array<{ title: string; items: Array<[string, string]> }> = [['Продукт', [['Возможности', '/#showcase'], ['Как это работает', '/#how-it-works']]], ['Для студентов', [['Сегодня', '/today'], ['Расписание', '/week'], ['Пропуски', '/absences']]], ['Роли', [['Преподаватели', '/#teachers'], ['Университеты', '/#universities']]]].map(([title, items]) => ({ title: title as string, items: items as Array<[string, string]> }));

export function PublicFooter() { return <footer className="border-t border-slate-200 bg-white px-6 py-12"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><div className="flex items-center gap-2 text-lg font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600 text-sm text-white">Н</span>НаПаре</div><p className="mt-3 max-w-xs text-sm text-slate-500">Цифровая платформа университета</p></div>{footerColumns.map(({ title, items }) => <div key={title}><h2 className="text-sm font-semibold text-slate-900">{title}</h2><div className="mt-3 grid gap-2">{items.map(([label, href]) => <Link key={label} href={href} className="text-sm text-slate-500 hover:text-slate-900">{label}</Link>)}</div></div>)}<div><h2 className="text-sm font-semibold text-slate-900">Поддержка</h2><a href="mailto:support@napare.ru" className="mt-3 block text-sm text-slate-500 hover:text-slate-900">support@napare.ru</a><p className="mt-5 text-xs text-slate-400">© 2026 НаПаре</p></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-slate-200 pt-6 text-xs text-slate-400">Использование платформы регулируется условиями университета и действующим законодательством.</div></footer>; }
