'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiFetchList } from '@/lib/api';
import { Badge, Card, EmptyState, RequestState, Skeleton } from '@/components/ui';

interface AuditItem { id: string; userId: string; action: string; entity: string; entityId: string; oldValues?: Record<string, unknown>; newValues?: Record<string, unknown>; source?: string; createdAt: string; }
function values(value?: Record<string, unknown>) { if (!value || !Object.keys(value).length) return 'Нет данных'; return Object.entries(value).map(([key, item]) => `${key}: ${String(item)}`).join(' · '); }

export default function AuditLogPage() {
  const [items, setItems] = useState<AuditItem[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); apiFetchList<AuditItem>('/admin/audit-log?limit=100').then(setItems).catch((err) => setError(err instanceof Error ? err.message : 'Не удалось загрузить Audit Log.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); return value ? items.filter((item) => `${item.action} ${item.entity} ${item.entityId} ${item.userId}`.toLowerCase().includes(value)) : items; }, [items, query]);
  return <div className="mx-auto max-w-[1400px] space-y-6"><div className="flex items-center gap-2 text-sm text-slate-500"><Link href="/dashboard" className="hover:text-slate-900">Operations Center</Link><span>/</span><span className="text-slate-900">Audit Log</span></div><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Audit Log</h1><p className="mt-1 text-sm text-slate-500">Критические изменения: кто, что, когда, источник и diff значений.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск по событию или объекту" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-sky-500 focus:ring-2 focus:ring-sky-100 sm:max-w-xs" /></div>{loading ? <div className="space-y-3"><Skeleton className="h-16" /><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : error ? <RequestState title="Не удалось загрузить Audit Log" description={error} onRetry={load} /> : !filtered.length ? <EmptyState title="Изменений не найдено" description="Критические изменения появятся после действий администраторов." /> : <Card padding="sm"><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Когда</th><th className="px-4 py-3">Кто</th><th className="px-4 py-3">Изменение</th><th className="px-4 py-3">Источник</th><th className="px-4 py-3">Старое значение</th><th className="px-4 py-3">Новое значение</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id} className="align-top hover:bg-slate-50"><td className="whitespace-nowrap px-4 py-4 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString('ru-RU')}</td><td className="px-4 py-4"><p className="font-medium text-slate-900">{item.userId}</p></td><td className="px-4 py-4"><p className="font-semibold text-slate-900">{item.action}</p><p className="mt-1 text-xs text-slate-500">{item.entity} · {item.entityId}</p></td><td className="px-4 py-4"><Badge variant="slate">{item.source || 'system'}</Badge></td><td className="max-w-[240px] px-4 py-4 text-xs leading-5 text-slate-600">{values(item.oldValues)}</td><td className="max-w-[240px] px-4 py-4 text-xs leading-5 text-slate-600">{values(item.newValues)}</td></tr>)}</tbody></table></div></Card>}</div>;
}
