'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiFetchList } from '@/lib/api';
import { Badge, Card, EmptyState, RequestState, Skeleton } from '@/components/ui';

interface Faculty { id: string; name: string; }
interface Group { id: string; name: string; facultyId: string; }
interface User { id: string; firstName: string; lastName: string; email: string; role?: string; groupId?: string; }

export default function StructurePage() {
  const [faculties, setFaculties] = useState<Faculty[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); Promise.all([apiFetchList<Faculty>('/admin/faculties?limit=100'), apiFetchList<Group>('/admin/groups?limit=100'), apiFetchList<User>('/admin/users?limit=100')]).then(([facultyItems, groupItems, userItems]) => { setFaculties(facultyItems); setGroups(groupItems); setUsers(userItems); }).catch((err) => setError(err instanceof Error ? err.message : 'Не удалось загрузить структуру университета.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const normalized = query.trim().toLowerCase(); const visible = useMemo(() => faculties.map((faculty) => ({ ...faculty, groups: groups.filter((group) => group.facultyId === faculty.id).map((group) => ({ ...group, users: users.filter((user) => user.groupId === group.id) })) })).map((faculty) => ({ ...faculty, groups: faculty.groups.filter((group) => !normalized || `${faculty.name} ${group.name} ${group.users.map((user) => `${user.firstName} ${user.lastName}`).join(' ')}`.toLowerCase().includes(normalized)) })).filter((faculty) => !normalized || faculty.groups.length || faculty.name.toLowerCase().includes(normalized)), [faculties, groups, users, normalized]);
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  return <div className="mx-auto max-w-[1200px] space-y-6"><div><p className="text-sm font-medium text-sky-700">University Structure</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">University → Faculty → Group → Users</h1><p className="mt-1 text-sm text-slate-500">Поиск по дереву и быстрый выбор объектов для массовых операций.</p></div><div className="flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск факультета, группы или пользователя" className="h-11 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" />{selected.length > 0 && <div className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm text-slate-600"><span>Выбрано: {selected.length}</span><button type="button" onClick={() => setSelected([])} className="font-semibold text-sky-700">Сбросить</button></div>}</div>{loading ? <div className="space-y-3"><Skeleton className="h-20" /><Skeleton className="h-20" /><Skeleton className="h-20" /></div> : error ? <RequestState title="Не удалось загрузить структуру" description={error} onRetry={load} /> : !visible.length ? <EmptyState title="Ничего не найдено" description="Измените поисковый запрос." /> : <div className="space-y-3">{visible.map((faculty) => <Card key={faculty.id} padding="sm"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><div><h2 className="font-bold text-slate-950">{faculty.name}</h2><p className="mt-1 text-xs text-slate-500">{faculty.groups.length} групп</p></div><Badge variant="slate">Faculty</Badge></div><div className="mt-2 divide-y divide-slate-100">{faculty.groups.length ? faculty.groups.map((group) => <div key={group.id} className="py-3"><div className="flex items-center justify-between gap-3"><label className="flex items-center gap-3"><input type="checkbox" checked={selected.includes(group.id)} onChange={() => toggle(group.id)} aria-label={`Выбрать группу ${group.name}`} /><span className="font-semibold text-slate-900">{group.name}</span></label><span className="text-xs text-slate-500">{group.users.length} пользователей</span></div>{group.users.length > 0 && <div className="mt-2 ml-7 flex flex-wrap gap-2">{group.users.slice(0, 6).map((user) => <span key={user.id} className="rounded-lg bg-slate-50 px-2 py-1 text-xs text-slate-600">{user.firstName} {user.lastName}</span>)}{group.users.length > 6 && <span className="px-2 py-1 text-xs text-slate-400">+{group.users.length - 6}</span>}</div>}</div>) : <p className="py-3 text-sm text-slate-500">Групп нет.</p>}</div></Card>)}</div>}</div>;
}
