'use client';

import Link from 'next/link';
import { useState } from 'react';

export function PublicNavigation() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 py-2 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-2.5 text-lg font-bold text-slate-900" aria-label="НаПаре, на главную"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-600 text-sm text-white">Н</span>НаПаре</Link><nav className="hidden xl:flex"><Link href="/" className="rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-100 hover:text-slate-950">О платформе</Link></nav><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100 sm:block">Войти</Link><button type="button" onClick={() => setOpen(true)} className="h-11 w-11 rounded-lg text-xl text-slate-700 hover:bg-slate-100 xl:hidden" aria-label="Открыть меню">☰</button></div>{open && <div className="fixed inset-0 z-50 bg-white p-5 xl:hidden"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-lg font-bold text-slate-900" onClick={() => setOpen(false)}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-600 text-sm text-white">Н</span>НаПаре</Link><button type="button" onClick={() => setOpen(false)} className="h-11 w-11 rounded-lg text-2xl text-slate-700 hover:bg-slate-100" aria-label="Закрыть меню">×</button></div><nav className="mt-8"><Link href="/" onClick={() => setOpen(false)} className="block rounded-xl px-4 py-3 text-lg text-slate-700 hover:bg-slate-100">О платформе</Link></nav><div className="absolute inset-x-5 bottom-6 border-t border-slate-200 pt-5"><Link href="/login" onClick={() => setOpen(false)} className="block rounded-xl bg-sky-600 px-4 py-3 text-center font-semibold text-white">Войти</Link></div></div>}</header>;
}

export function PublicFooter() { return <footer className="border-t border-slate-200 bg-white px-6 py-10"><div className="mx-auto grid max-w-7xl gap-8 text-sm sm:grid-cols-3"><div><div className="flex items-center gap-2 font-bold text-slate-900"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-sky-600 text-white">Н</span>НаПаре</div><p className="mt-3 text-slate-500">Цифровая платформа университета</p></div><div><h2 className="font-semibold text-slate-900">Продукт</h2><Link href="/" className="mt-3 block text-slate-500 hover:text-slate-900">О платформе</Link><Link href="/login" className="mt-2 block text-slate-500 hover:text-slate-900">Войти в кабинет</Link></div><div><h2 className="font-semibold text-slate-900">Поддержка</h2><a href="mailto:support@napare.ru" className="mt-3 block text-slate-500 hover:text-slate-900">support@napare.ru</a><p className="mt-5 text-xs text-slate-400">© 2026 НаПаре</p></div></div></footer>; }
